defaults: grpo-apertus1p5-8b-1n4g-megatron-probe.yaml
grpo:
  num_prompts_per_step: 4
  max_val_samples: null
  skip_reference_policy_logprobs_calculation: true
loss_fn:
  reference_policy_kl_penalty: 0
policy:
  train_global_batch_size: 16
  generation:
    vllm_cfg:
      async_engine: true
      expose_http_server: true
      http_server_serving_chat_kwargs:
        chat_template: /capstor/store/cscs/swissai/infra01/apertus_1p5/hf_checkpoints/ap1p5-8b-sft-256k-adam-lr6e-5-constant-128n_4200/chat_template.jinja
data:
  shuffle: false
  num_workers: 0
  train:
    dataset_name: NemoGymDataset
    data_path: examples/nemo_gym/apertus/math_with_judge_example_agent.jsonl
    repeat: 8
    split_validation_size: null
  validation:
    data_path: examples/nemo_gym/apertus/math_with_judge_example_agent.jsonl
  default:
    dataset_name: NemoGymDataset
    env_name: nemo_gym
    prompt_file: null
    processor: nemo_gym_data_processor
env:
  should_use_nemo_gym: true
  nemo_gym:
    port_range_low: 11001
    port_range_high: 20000
    config_paths:
    - responses_api_models/vllm_model/configs/vllm_model_for_training.yaml
    - resources_servers/math_with_judge/configs/math_with_judge.yaml
    math_with_judge:
      resources_servers:
        math_with_judge:
          should_use_judge: false
    policy_model:
      responses_api_models:
        vllm_model:
          uses_reasoning_parser: false
          extra_body:
            chat_template_kwargs:
              enable_thinking: false
logger:
  log_dir: logs/grpo-apertus-gym
