defaults: grpo-apertus1p5-70b-16n4g-megatron-tp2pp4-sc-bench-lag1.yaml

loss_fn:
  truncated_importance_sampling_type: tis
  truncated_importance_sampling_ratio: 2.0

logger:
  wandb:
    name: nemo-rl-70b-tp2pp4-tis2-${oc.env:AP_ANSWER_MARKER,boxed}-lag1-seed${oc.env:AP_SEED,42}
